### PR TITLE
Fix a typo in the map reference line.

### PR DESCRIPTION
**Pull request by gravyboat**

### CODE REVIEW

**Comment by gravyboat** [comment]
Resolves #13.

**Comment by gravyboat** [comment]
@nmadhok/@iggy Please merge this when you get a chance today.

**Comment by nmadhok** [comment]
@gravyboat Thanks!

**Comment by gravyboat** [comment]
Yeah of course, thanks for getting this merged in!

**Comment by iggy** [comment]
I can't merge things... silly Forrest

**Comment by gravyboat** [comment]
@iggy we should ask @whiteinge to fix that!

**Comment by whiteinge** [comment]
Oh, man. How did that slip through? @iggy invited, good sir! With great power comes too often repeated Spiderman movie quotes...

**Comment by gravyboat** [comment]
Awesome thanks @whiteinge!

**Pull request merged**
