### PR TITLE
Add tests, fix configuration on Debian

### PR DESCRIPTION
**Pull request by n-rodriguez**
This PR fixes : https://github.com/saltstack-formulas/vim-formula/issues/33

### CODE REVIEW

**Comment by n-rodriguez** [comment]
Ok. I merge it. Thank you!

**Comment by aboe76** [comment]
Give @thatch45 some time to response, give me a ping in a day or two then I will merge it.

**Comment by n-rodriguez** [comment]
Ok. Thanks!

**Comment by n-rodriguez** [comment]
ping!

**Comment by aboe76** [comment]
@n-rodriguez pong

**Pull request merged**
