### PR TITLE
Allow installation of arbitrary plugins using vim-plug and allow for managing user config

### PR DESCRIPTION
**Pull request by WhiteAbeLincoln**
These are some changes that I made for my personal dotfiles that I thought I should contribute back to the community.

Like the title says, this allows for installation of arbitrary plugins using [vim-plug](https://github.com/junegunn/vim-plug), as well as management of user configurations as well as global configs.

A real-life usage example can be found in my [dotfiles](https://github.com/WhiteAbeLincoln/dotfiles/blob/master/pillar/vim.sls), and an example of user management can be found in the [example pillar file](https://github.com/WhiteAbeLincoln/salt-formula-vim/blob/master/pillar.example)

### CODE REVIEW

**Comment by WhiteAbeLincoln** [comment]
I realize that installing plugins is not the current focus of this repository, which bundles a select few plugins with the vim configuration, but I figured I should open the pull request and see what you guys think

**Comment by aboe76** [comment]
@WhiteAbeLincoln I like the idea of using vim-plug, can you update / rebase your pr?
so I can test it.

**Comment by noelmcloughlin** [comment]
This PR would be nice

**Comment by daks** [comment]
Will this plugin installation work 'systemwide'? I'm used to `vim-plug` but only in the context of my user.

**Comment by noelmcloughlin** [comment]
> Will this plugin installation work 'systemwide'? I'm used to `vim-plug` but only in the context of my user.

Hmm, the pillar.example only lists a `vagrant` user as example. I would like system wide scope also, but a future pr is okay.

**Comment by aboe76** [comment]
@WhiteAbeLincoln can you please rebase?

**Pull request closed without merging**
